"""add_video_metadata

Revision ID: 132f83e0a398
Revises: 53dc896f934c
Create Date: 2026-07-11 16:08:22.891939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132f83e0a398'
down_revision: Union[str, Sequence[str], None] = '53dc896f934c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_chunks', sa.Column('chunk_type', sa.String(length=32), nullable=False))
    op.add_column('video_chunks', sa.Column('metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_video_chunks_chunk_type'), 'video_chunks', ['chunk_type'], unique=False)
    op.drop_column('video_chunks', 'embedding')
    op.add_column('videos', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('resolution', sa.String(length=50), nullable=True))
    op.add_column('videos', sa.Column('fps', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('codec', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'codec')
    op.drop_column('videos', 'fps')
    op.drop_column('videos', 'resolution')
    op.drop_column('videos', 'duration')
    op.add_column('video_chunks', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_video_chunks_chunk_type'), table_name='video_chunks')
    op.drop_column('video_chunks', 'metadata')
    op.drop_column('video_chunks', 'chunk_type')
    # ### end Alembic commands ###
