"""add_is_admin_and_sha256

Revision ID: 21ffe60a8391
Revises: 68d0d6386fa7
Create Date: 2026-07-11 17:15:28.618679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ffe60a8391'
down_revision: Union[str, Sequence[str], None] = '68d0d6386fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('videos', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_videos_sha256'), 'videos', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_sha256'), table_name='videos')
    op.drop_column('videos', 'sha256')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
