"""baseline

Revision ID: 53dc896f934c
Revises: 
Create Date: 2026-07-11 16:07:20.650326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dc896f934c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_chunks', sa.Column('chunk_type', sa.String(length=32), nullable=False))
    op.add_column('video_chunks', sa.Column('metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_video_chunks_chunk_type'), 'video_chunks', ['chunk_type'], unique=False)
    op.drop_column('video_chunks', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_chunks', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_video_chunks_chunk_type'), table_name='video_chunks')
    op.drop_column('video_chunks', 'metadata')
    op.drop_column('video_chunks', 'chunk_type')
    # ### end Alembic commands ###
